# Generated by Django 4.2.3 on 2023-10-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0003_drug_dosage_drug_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
