# Generated by Django 4.2.3 on 2023-10-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0007_specialization_alter_doctor_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
