# Generated by Django 4.2.3 on 2023-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0008_remove_doctor_specialization_delete_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialisation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
