# Generated by Django 4.2.3 on 2023-10-17 11:38

import PharmaLink.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0009_doctor_specialisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescribe',
        ),
        migrations.AddField(
            model_name='prescription',
            name='valid_till_date',
            field=models.DateField(default=PharmaLink.models.default_valid_till_date),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_precribed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
