# Generated by Django 4.2.3 on 2023-10-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0011_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='reorder_level',
        ),
    ]
