# Generated by Django 4.2.3 on 2023-10-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0012_remove_inventory_reorder_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientFeedback',
        ),
    ]
