# Generated by Django 4.2.3 on 2023-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0014_pharmacyclerk_address_pharmacyclerk_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
