# Generated by Django 4.2.3 on 2023-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0015_patients_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'AdminHOD'), (2, 'Pharmacist'), (3, 'Doctor'), (5, 'Patients')], default=1, max_length=10),
        ),
        migrations.DeleteModel(
            name='PharmacyClerk',
        ),
    ]
