# Generated by Django 4.2.3 on 2023-10-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0016_alter_customuser_user_type_delete_pharmacyclerk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispense',
            name='drug_id',
        ),
        migrations.AddField(
            model_name='dispense',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='PharmaLink.drug'),
        ),
    ]
