# Generated by Django 4.2.3 on 2023-10-27 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0018_alter_dispense_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='dispense_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
