# Generated by Django 4.2.3 on 2023-10-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PharmaLink', '0019_alter_dispense_dispense_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispense',
            name='taken',
        ),
    ]
